### ISSUE TITLE
UnicodeEncodeError for Redeemer.py

### ISSUE THREAD

**Issue by nathannli** [DapperDog/PokemonTCGOCodeChecker#1]
Found a possible break case with the redeemer code.

When running the code that contains unredeemed codes, the code crashes on line 49 with UnicodeEncodeError. 

![aa](https://user-images.githubusercontent.com/17099069/44700839-6817c680-aa59-11e8-9139-ef7a02391878.jpg)

For already redeemed codes, it works fine.

A potential fix that I'm currently using is changing line 49 to
```
print item.encode('utf-8').strip()
```

Thanks for your work.

**Comment by DapperDog** [comment]
Sorry for the delay, I haven't been able to reproduce this yet, do you have the code that gave you this error?

( my regression test is ~1000 codes with ~50 unique codes)

**Comment by DapperDog** [comment]
Lol womp womp, I didn't realise this was for the redeemer, thanks for pointing this out.

99% of the people who use this script are shops / code sellers / re-sellers, I made the redeemer just to see if I could actually redeem codes, and a friend who actually plays ptcgo requested it.

Thanks for the catch :)

**Comment by DapperDog** [comment]
Fixed in 228c70b7cf83a5feeff4ae94497cd4d308dd3087
