### ISSUE TITLE
Script doesn't run - Validator closes straightaway

### ISSUE THREAD

**Issue by UnitedStudios** [DapperDog/PokemonTCGOCodeChecker#3]
I've just tried to run the validator and it instantly opens and closes and doesn't run. Has this avenue of verifying been blocked off?

**Comment by nyxtyr** [comment]
I believe it has, I attempted to update the URL's and still same issue.

**Comment by DapperDog** [comment]
> I believe it has, I attempted to update the URL's and still same issue.

This version hasn't been supported since April  2023 when they made the switch to PTCGOLive and started using recaptcha V3 in their web API.

I have newer version that work but are no longer public as I got too many emails from folks begging for stuff / asking for tech support 👎
